### PR TITLE
Add pyproject.toml to config black line length

### PR DESCRIPTION
**Pull request by janosh**
[Follow up to this comment](https://github.com/hackingmaterials/automatminer/pull/245#issuecomment-545244651).

### CODE REVIEW

**Comment by janosh** [comment]
[Like you said](https://github.com/hackingmaterials/automatminer/pull/245#issuecomment-545244651), there seems to be a problem with code style. But I'm not sure it's the code. The `dev_scripts/run_code_style_check.sh` script doesn't log any output, suggesting that maybe it's not running as expected?

```sh
#!/bin/bash -eo pipefail
source dev_scripts/setup_env_dev.sh
source dev_scripts/run_code_style_check.sh
WARNING: You are using pip version 19.3; however, version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exited with code 1
```

Similarly, the tests fail with something that seems unrelated to the changes in this PR.

```sh
RuntimeError: implement_array_function method already has a docstring
2019-10-23 09:43:30,877 - ERROR - environment variable CODACY_PROJECT_TOKEN is not defined.
Exited with code 1
```

**Comment by ardunn** [comment]
### Coce style
Ok so @janosh I ssh'd into your build and ran the script manually:
```
(test_env) circleci@5995ac2386af:~/py372_automatminer$ source dev_scripts/run_code_style_check.sh
Code misformatted!
automatminer/presets.py:143:86: E501 line too long (88 > 85 characters)
automatminer/tests/test_pipeline.py:79:86: E501 line too long (86 > 85 characters)
automatminer/featurization/tests/test_sets.py:74:86: E501 line too long (88 > 85 characters)
automatminer/preprocessing/feature_selection.py:223:86: E501 line too long (86 > 85 characters)
automatminer/automl/adaptors.py:204:86: E501 line too long (87 > 85 characters)
```

I just don't think CircleCI prints the output sometimes if a command exits with code 1.


### Tests failing
The tests actually passed. The environment variable thing is another CircleCI problem ([I posted a question on the forum about it](https://discuss.circleci.com/t/environment-variable-not-set-if-build-triggered-by-someone-who-is-not-me/33048)). Don't worry about it, when the code_style stuff is fixed I'll just merge it and trigger the tests myself (which would fix this env var issue until CircleCI gets back to me)  :)

**Comment by janosh** [comment]
Sorry, this is my mistake. Looks like we need a `pyproject.toml` file after all since [that's the only config file `black` supports](https://github.com/flying-sheep/awesome-python-packaging#code-style). Should have checked that as part of #245.

**Comment by janosh** [comment]
> would it be possible to revert the formatting on these files and just PR the config changes?

@ardunn DONE.

**Comment by janosh** [comment]
@ardunn Anything left to do here?

**Comment by ardunn** [comment]
@janosh thanks again!

**Pull request merged**
