### PR TITLE
Better handling of adding oxidation states to large structures.

### LINKED ISSUE #138: Oxidation states guessed twice
Currently oxidation states are guessed separately for structures and for compositions.

Instead, oxidation states should be guessed for structures only, with the oxidation state compositions taken from the precomputed structure.

### PR DESCRIPTION
**Pull request by utf**
I removed the custom oxidation state conversion featurizers and updated the code to use the latest improvements in pymatgen (materialsproject/pymatgen#1353) and matminer (hackingmaterials/matminer#339) so that large structures are handled gracefully.

This pull request (along with the matminer improvements) should also fix #138, as now the compositions are always calculated directly from the structure (after oxidation states have been added).

We should hold off merging this until both the matminer and pymatgen PR have been merged.

### CODE REVIEW

**Comment by ardunn** [comment]
sweet thanks

**Comment by ardunn** [comment]
should be good to try this again yeah?

**Comment by utf** [comment]
Yeah, I'll take a look

**Comment by ardunn** [comment]
@utf when can we merge this? I ask bc mp_all is still failing production runs because of oxidconversion problems. Maybe when we have the newest pymatgen in matminer (https://github.com/hackingmaterials/matminer/pull/346) will this PR be ready?

**Pull request merged**
